version: '3.7'
services:
    rest_service:
        depends_on:
            - devpg
        build: ./
        environment:
            POSTGRES_HOST: "devpg"
        ports:
         - 8080:8080
    devpg:
        container_name: dev-postgres
        image: postgres:latest
        volumes:
            - ~/docker/volumes/example/postgres:/var/lib/postgresql/data/
        command:
            - 'postgres'
            - '-c'
            - 'max_prepared_transactions=100'
        ports:
            - 5433:5432
        environment:
            POSTGRES_DB: resttest
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 23happyme
        networks:
            - default
    zookeeper:
        image: zookeeper
        expose:
            - "2181"
    kafka:
        image: bitnami/kafka
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://1.2.3.4:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
            KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
        depends_on:
            - zookeeper
        volumes:
            - ./:/etc/kafka
