spring:
  datasource:
#    platform: postgres
    username: postgres
    password: 23happyme
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/resttest
    driverClassName: org.postgresql.Driver

logging:
  level:
    web: trace

